
import json
import re
from datetime import datetime
from pathlib import Path

from cfg_model_builder import collect_raw_forced_assignments, normalize_user_constraints


def comp_label(cid, parsed_config):
    """Human-readable label for a component, e.g. 'turbine c1' or 'pump c3'."""
    comp = parsed_config["components"].get(cid, {})
    ctype = comp.get("type", "component")
    return f"{ctype} {cid}"


def res_label(rid, parsed_config):
    """Human-readable label for a reservoir, e.g. 'reservoir r1'."""
    return f"reservoir {rid}"


def build_iis_constraint_interpretation(parsed_config):
    """
    Build the interpretation dictionary dynamically from config.
    Keys are constraint names as they appear in the Pyomo model.
    """
    interp = {}
    res_ids = sorted(parsed_config["reservoirs"].keys())
    comp_ids = sorted(parsed_config["comp_ids"])
    active_ids = sorted(parsed_config["active_comps"])
    spill_ids = sorted(parsed_config["spills"])

    def wrap_iis_entry(binding_type, interpretation, trigger_risk):
        return {
            "type_of_binding": binding_type,
            "interpretation": interpretation,
            "triggering_forced_constraints": trigger_risk,
        }

    for rid in res_ids:
        rl = res_label(rid, parsed_config)
        interp[f"soft_low_{rid}"] = wrap_iis_entry(
            "lower bound (>=)",
            f"{rl} level must stay above a minimum threshold",
            f"Forced generation or other forced outflows may draw {rl} below the allowable minimum",
        )
        interp[f"soft_high_{rid}"] = wrap_iis_entry(
            "upper bound (<=)",
            f"{rl} level must stay below a maximum threshold",
            f"Forced pumping or other volume-retaining decisions may raise {rl} above the allowable maximum",
        )

    for cid in comp_ids:
        cl = comp_label(cid, parsed_config)
        comp = parsed_config["components"].get(cid, {})
        interp[f"q_upper_{cid}"] = wrap_iis_entry(
            "upper bound (<=)",
            f"{cl} flow cannot exceed its maximum capacity; if the unit is OFF, flow is forced to zero",
            f"Forcing {cl} ON may create a flow pattern that exceeds the allowable maximum",
        )
        if comp.get("type") != "spill":
            interp[f"q_min_on_{cid}"] = wrap_iis_entry(
                "lower bound (>=)",
                f"when {cl} is ON, it must operate above a minimum stable flow",
                f"Forcing {cl} ON when the system cannot supply the minimum required flow can create infeasibility",
            )

    for cid in active_ids:
        cl = comp_label(cid, parsed_config)
        comp = parsed_config["components"][cid]
        if comp["type"] == "turbine":
            trigger_risk = f"Forced {cl} operation may imply flow/head combinations outside the feasible generation region"
            interp[f"approx_{cid}"] = wrap_iis_entry(
                "upper bound (<=)",
                f"power generated by {cl} must remain within the feasible operating region defined by flow and head",
                trigger_risk,
            )
            interp[f"turbine_plane_{cid}"] = wrap_iis_entry(
                "upper bound (<=)",
                f"power generated by {cl} must remain within the feasible operating region defined by flow and head",
                trigger_risk,
            )
        else:
            trigger_risk = f"Forced {cl} operation may imply flow/head combinations outside the feasible pumping region"
            interp[f"approx_{cid}"] = wrap_iis_entry(
                "lower bound (>=)",
                f"{cl} power consumption must remain within the feasible operating region defined by flow and head",
                trigger_risk,
            )
            interp[f"pump_plane_{cid}"] = wrap_iis_entry(
                "lower bound (>=)",
                f"{cl} power consumption must remain within the feasible operating region defined by flow and head",
                trigger_risk,
            )

    for cid in active_ids:
        cl = comp_label(cid, parsed_config)
        interp[f"P_link_up_mode_{cid}"] = wrap_iis_entry(
            "upper bound (<=)",
            f"if {cl} is OFF, power is forced to zero; if ON, power is capped by its mode-specific upper bound",
            f"Forced {cl} operation may push actual power outside the mode-specific upper power limit",
        )
        interp[f"P_link_low_mode_{cid}"] = wrap_iis_entry(
            "lower bound (>=)",
            f"if {cl} is ON, power must stay above its mode-specific lower bound; if OFF, power is forced to zero",
            f"Forced {cl} operation may push actual power below the mode-specific lower power limit",
        )
        interp[f"P_link_up_aux_{cid}"] = wrap_iis_entry(
            "upper bound (<=)",
            f"links {cl} actual power to its auxiliary power under the ON/OFF mode logic",
            f"Forced {cl} operation may drive power above the auxiliary envelope",
        )
        interp[f"P_link_low_aux_{cid}"] = wrap_iis_entry(
            "lower bound (>=)",
            f"links {cl} actual power to its auxiliary power under the ON/OFF mode logic",
            f"Forced {cl} operation may drive power below the auxiliary envelope",
        )

    interp["exclusive_constraints"] = wrap_iis_entry(
        "upper bound (<=)",
        "certain mutually exclusive units cannot be ON at the same hour",
        "Forcing two mutually exclusive units ON simultaneously can create a direct conflict",
    )
    interp["exclusive_const"] = wrap_iis_entry(
        "upper bound (<=)",
        "certain mutually exclusive units cannot be ON at the same hour",
        "Forcing two mutually exclusive units ON simultaneously can create a direct conflict",
    )
    interp["upper_exclusive"] = wrap_iis_entry(
        "upper bound (<=)",
        "the upper turbine and pump cannot both be ON simultaneously",
        "Forcing both upper turbine and pump modes ON simultaneously can create a direct conflict",
    )

    for sid in spill_ids:
        cl = comp_label(sid, parsed_config)
        head_name = "weir_head_trigger" if len(spill_ids) == 1 else f"weir_head_trigger_{sid}"
        flow_name = "weir_qgen_trigger" if len(spill_ids) == 1 else f"weir_qgen_trigger_{sid}"
        interp[head_name] = wrap_iis_entry(
            "lower bound (>=)",
            f"{cl} can only operate when hydraulic trigger conditions are met",
            f"Forcing {cl} activation when trigger conditions are not satisfied, or forcing it OFF when conditions require activation, can create infeasibility",
        )
        interp[flow_name] = wrap_iis_entry(
            "lower bound (>=)",
            f"{cl} can only operate when hydraulic trigger conditions are met",
            f"Forcing {cl} activation when trigger conditions are not satisfied, or forcing it OFF when conditions require activation, can create infeasibility",
        )
        interp[f"head_trigger_{sid}"] = wrap_iis_entry(
            "lower bound (>=)",
            f"{cl} can only operate when hydraulic trigger conditions are met",
            f"Forcing {cl} activation when trigger conditions are not satisfied, or forcing it OFF when conditions require activation, can create infeasibility",
        )
        interp[f"flow_trigger_{sid}"] = wrap_iis_entry(
            "lower bound (>=)",
            f"{cl} can only operate when hydraulic trigger conditions are met",
            f"Forcing {cl} activation when trigger conditions are not satisfied, or forcing it OFF when conditions require activation, can create infeasibility",
        )

    interp["water_balance"] = wrap_iis_entry(
        "equality (=)",
        "reservoir storage condition must satisfy mass balance rule over time",
        "Consecutive forced generation, pumping, or spill decisions may create flow patterns that cannot satisfy mass balance",
    )
    interp["head_eq"] = wrap_iis_entry(
        "equality (=)",
        "reservoir head is determined by reservoir volume",
        "Forced operation may drive reservoir volume to values that imply infeasible head values",
    )
    interp["init_storage"] = wrap_iis_entry(
        "equality (=)",
        "reservoir volume at t=0 is fixed to the configured initial storage",
        "Forcing units connected to the reservoir to be ON at the first time step may cause contradiction in the model",
    )
    interp["init_head"] = wrap_iis_entry(
        "equality (=)",
        "reservoir head/water level at t=0 is fixed to the configured initial water level",
        "Forcing units connected to the reservoir to be ON at the first time step may cause contradiction in the model",
    )
    interp["init_flow"] = wrap_iis_entry(
        "equality (=)",
        "unit flow at t=0 is fixed to the configured initial flow",
        "Forcing a unit ON when initial flow is fixed to zero can create infeasibility",
    )
    interp["init_constraints"] = wrap_iis_entry(
        "equality (=)",
        "initial storage, head, and flow values are fixed at t=0",
        "Forcing units connected to a reservoir to be ON at the first time step may cause a contradiction",
    )
    interp["init_cond"] = wrap_iis_entry(
        "equality (=)",
        "initial storage, head, and flow values are fixed at t=0",
        "Forcing units connected to a reservoir to be ON at the first time step may cause a contradiction",
    )
    interp["keep_p1"] = wrap_iis_entry(
        "equality (=)",
        "keeps phase-1 minimum safety violation fixed during phase-2 optimization",
        "Keeping a phase-1 lock can conflict with later forced adjustments if the original slack is exhausted",
    )

    return interp


def build_binding_interpretation(parsed_config):
    """Build binding / non-binding interpretation dicts dynamically."""
    binding = {}
    non_binding = {}
    res_ids = sorted(parsed_config["reservoirs"].keys())
    active_ids = sorted(parsed_config["active_comps"])
    comp_ids = sorted(parsed_config["comp_ids"])
    spill_ids = sorted(parsed_config["spills"])

    for rid in res_ids:
        rl = res_label(rid, parsed_config)
        binding[f"soft_low_{rid}"] = f"{rl} level is at or near the minimum allowable threshold"
        non_binding[f"soft_low_{rid}"] = f"{rl} level is comfortably above the minimum allowable threshold"
        binding[f"soft_high_{rid}"] = f"{rl} level is at or near the maximum allowable threshold"
        non_binding[f"soft_high_{rid}"] = f"{rl} level is comfortably below the maximum allowable threshold"

    for cid in comp_ids:
        cl = comp_label(cid, parsed_config)
        comp = parsed_config["components"].get(cid, {})
        binding[f"q_upper_{cid}"] = f"{cl} operates at its maximum allowable flow"
        non_binding[f"q_upper_{cid}"] = f"{cl} is below its maximum allowable flow"
        if comp.get("type") != "spill":
            binding[f"q_min_on_{cid}"] = f"{cl} is ON at its minimum stable flow"
            non_binding[f"q_min_on_{cid}"] = f"{cl} is ON above its minimum stable flow"

    for cid in active_ids:
        cl = comp_label(cid, parsed_config)
        binding[f"approx_{cid}"] = f"{cl} is on the boundary of the feasible power region"
        non_binding[f"approx_{cid}"] = f"the hyperplane is not the active power limit for {cl}"
        if parsed_config["components"][cid]["type"] == "turbine":
            binding[f"turbine_plane_{cid}"] = f"{cl} is on the boundary of the feasible power region"
            non_binding[f"turbine_plane_{cid}"] = f"the hyperplane is not the active power limit for {cl}"
        else:
            binding[f"pump_plane_{cid}"] = f"{cl} is on the boundary of the feasible power region"
            non_binding[f"pump_plane_{cid}"] = f"the hyperplane is not the active power limit for {cl}"
        binding[f"P_link_up_mode_{cid}"] = f"{cl} is ON at its upper power limit, or OFF at zero power"
        non_binding[f"P_link_up_mode_{cid}"] = f"{cl} is not pinned to its mode-specific upper power limit"
        binding[f"P_link_low_mode_{cid}"] = f"{cl} is ON at its lower power limit, or OFF at zero power"
        non_binding[f"P_link_low_mode_{cid}"] = f"{cl} is not pinned to its mode-specific lower power limit"
        binding[f"P_link_up_aux_{cid}"] = f"{cl} power is capped by the auxiliary power envelope"
        non_binding[f"P_link_up_aux_{cid}"] = f"{cl} is below the auxiliary upper envelope; another limit is controlling"
        binding[f"P_link_low_aux_{cid}"] = f"{cl} power is pinned by the auxiliary power envelope"
        non_binding[f"P_link_low_aux_{cid}"] = f"{cl} still has room above the auxiliary lower envelope"

    binding["exclusive_constraints"] = "mutually exclusive components cannot both be ON simultaneously"
    non_binding["exclusive_constraints"] = "only one exclusive component is active, or both are OFF"
    binding["exclusive_const"] = "mutually exclusive components cannot both be ON simultaneously"
    non_binding["exclusive_const"] = "only one exclusive component is active, or both are OFF"
    binding["upper_exclusive"] = "upper turbine and pump cannot both be ON simultaneously"
    non_binding["upper_exclusive"] = "only one upper-unit mode is active, or both are OFF"

    for sid in spill_ids:
        cl = comp_label(sid, parsed_config)
        head_name = "weir_head_trigger" if len(spill_ids) == 1 else f"weir_head_trigger_{sid}"
        flow_name = "weir_qgen_trigger" if len(spill_ids) == 1 else f"weir_qgen_trigger_{sid}"
        binding[head_name] = f"{cl} must be active because head trigger condition is met"
        binding[head_name] = f"{cl} is forced ON because the head trigger condition is met"
        non_binding[head_name] = f"the head trigger condition is not met; {cl} is not forced"
        binding[flow_name] = f"{cl} is forced ON because the flow trigger condition is met"
        non_binding[flow_name] = f"the flow trigger condition is not met; {cl} is not forced"
        binding[f"head_trigger_{sid}"] = f"{cl} is forced ON because the head trigger condition is met"
        non_binding[f"head_trigger_{sid}"] = f"the head trigger condition is not met; {cl} is not forced"
        binding[f"flow_trigger_{sid}"] = f"{cl} is forced ON because the flow trigger condition is met"
        non_binding[f"flow_trigger_{sid}"] = f"the flow trigger condition is not met; {cl} is not forced"

    binding["water_balance"] = "reservoir water balance is satisfied at each hour"
    binding["water_balance"] = "reservoir storage satisfies the mass balance rule at this hour"
    non_binding["water_balance"] = "reservoir storage balance is not the active restriction at this hour"
    binding["head_eq"] = "reservoir head is fixed by the storage-volume relation"
    non_binding["head_eq"] = "the storage-volume relation is not the active restriction"
    binding["init_constraints"] = "initial storage, head, and flow values are fixed at t=0"
    non_binding["init_constraints"] = "the initial condition is not the active restriction"
    binding["init_cond"] = "initial storage, head, and flow values are fixed at t=0"
    non_binding["init_cond"] = "the initial condition is not the active restriction"

    return binding, non_binding


def iis_constraint_family(constraint_name):
    if not isinstance(constraint_name, str):
        return ""
    match = re.match(r"^([A-Za-z0-9_]+)", constraint_name.strip())
    return match.group(1) if match else constraint_name.strip()


def iis_constraint_hour(constraint_name):
    if not isinstance(constraint_name, str):
        return None
    match = re.search(r"\(([^)]*)\)", constraint_name)
    if not match:
        return None
    for token in match.group(1).strip().split(","):
        token = token.strip()
        try:
            return int(token)
        except (TypeError, ValueError):
            continue
    return None


def iis_constraint_tokens(constraint_name):
    if not isinstance(constraint_name, str):
        return []
    match = re.search(r"\(([^)]*)\)", constraint_name)
    if not match:
        return []
    return [token.strip() for token in match.group(1).split(",") if token.strip()]


def describe_init_cond_index(idx_value, parsed_config):
    try:
        idx = int(idx_value)
    except (TypeError, ValueError):
        return None

    res_ids = sorted(parsed_config["reservoirs"].keys())
    comp_ids = [
        cid for cid in parsed_config["comp_ids"]
        if parsed_config["components"][cid]["type"] != "spill"
    ]

    n_res = len(res_ids)
    if 1 <= idx <= n_res:
        rid = res_ids[idx - 1]
        return f"initial storage of {res_label(rid, parsed_config)}"
    if n_res < idx <= 2 * n_res:
        rid = res_ids[idx - n_res - 1]
        return f"initial water level of {res_label(rid, parsed_config)}"

    flow_offset = 2 * n_res
    if flow_offset < idx <= flow_offset + len(comp_ids):
        cid = comp_ids[idx - flow_offset - 1]
        return f"initial flow of {comp_label(cid, parsed_config)}"

    return None


def component_reservoir_details(cid, parsed_config):
    comp = parsed_config["components"].get(cid, {})
    reservoirs = parsed_config.get("reservoirs", {})
    details = []

    source = comp.get("from")
    target = comp.get("to")
    if source in reservoirs:
        details.append(f"source {res_label(source, parsed_config)}")
    if target in reservoirs:
        details.append(f"receiving {res_label(target, parsed_config)}")

    return details


def describe_iis_constraint_entry(constraint_name, parsed_config):
    family = iis_constraint_family(constraint_name)
    tokens = iis_constraint_tokens(constraint_name)
    details = []

    if family in {"water_balance", "head_eq"} and tokens:
        rid = tokens[0]
        details.append(res_label(rid, parsed_config))
    elif family in {"init_cond", "init_constraints"} and tokens:
        decoded = describe_init_cond_index(tokens[0], parsed_config)
        if decoded:
            details.append(decoded)
            if decoded.startswith("initial flow of "):
                for cid in parsed_config["comp_ids"]:
                    if comp_label(cid, parsed_config) in decoded:
                        details.extend(component_reservoir_details(cid, parsed_config))
                        break
    elif family == "exclusive_const" and tokens:
        try:
            pair_idx = int(tokens[0])
            pairs = parsed_config.get("exclusive_pairs", [])
            if 0 <= pair_idx < len(pairs):
                pair = pairs[pair_idx]
                details.append("exclusive pair: " + ", ".join(comp_label(cid, parsed_config) for cid in pair))
        except (TypeError, ValueError):
            pass
    elif family.startswith(("q_upper_", "q_min_on_", "turbine_plane_", "pump_plane_", "P_link_")):
        cid = family.split("_")[-1]
        if cid in parsed_config["components"]:
            details.append(comp_label(cid, parsed_config))
            details.extend(component_reservoir_details(cid, parsed_config))
    elif family.startswith(("soft_low_", "soft_high_")):
        rid = family.split("_")[-1]
        if rid in parsed_config["reservoirs"]:
            details.append(res_label(rid, parsed_config))
    elif family.startswith(("flow_trigger_", "head_trigger_")):
        sid = family.split("_")[-1]
        if sid in parsed_config["components"]:
            details.append(comp_label(sid, parsed_config))

    return details


def iis_report_family(constraint_name, parsed_config):
    family = iis_constraint_family(constraint_name)
    if family not in {"init_cond", "init_constraints"}:
        return family

    tokens = iis_constraint_tokens(constraint_name)
    if not tokens:
        return family

    decoded = describe_init_cond_index(tokens[0], parsed_config)
    if decoded is None:
        return family
    if decoded.startswith("initial storage of "):
        return "init_storage"
    if decoded.startswith("initial water level of "):
        return "init_head"
    if decoded.startswith("initial flow of "):
        return "init_flow"
    return family


def explain_iis_constraints(constraint_names, iis_interp, parsed_config):
    grouped = {}
    for name in constraint_names:
        family = iis_report_family(name, parsed_config)
        entry = grouped.setdefault(family, {"constraint": family, "hours": set(), "details": set(), "entries": set()})
        hour = iis_constraint_hour(name)
        if hour is not None:
            entry["hours"].add(hour)
        for detail in describe_iis_constraint_entry(name, parsed_config):
            entry["details"].add(detail)
        entry["entries"].add(name)

    out = []
    for family in sorted(grouped):
        row = iis_interp.get(family, {})
        hours_sorted = sorted(grouped[family]["hours"])
        out.append({
            "constraint": family,
            "type_of_binding": row.get("type_of_binding", "unknown"),
            "hour": hours_sorted if hours_sorted else [],
            "affected_items": sorted(grouped[family]["details"]),
            "entries": sorted(grouped[family]["entries"]),
            "explanation": row.get("interpretation", "no interpretation found"),
            "forced_constraints_that_can_trigger_iis": row.get("triggering_forced_constraints", "no trigger text found"),
        })
    return out


def format_user_request_changes(user_constraints, spill_control, parsed_config):
    comp_ids = sorted(parsed_config["comp_ids"])
    spill_ids = sorted(parsed_config["spills"])
    horizon = parsed_config["N_p"]

    raw = collect_raw_forced_assignments(
        raw_const=user_constraints,
        comp_ids=comp_ids,
        raw_spill_control=spill_control,
        spill_ids=spill_ids,
        horizon=horizon,
    )

    grouped = {}
    for row in raw:
        var = row["var"]
        value = int(row["value"])
        hour = int(row["hour"])
        grouped.setdefault((var, value), set()).add(hour)

    changes = []
    for var, value in sorted(grouped):
        changes.append({
            "variable": var,
            "hour": sorted(grouped[(var, value)]),
            "forced_value": value,
        })
    return changes


def mode_changes(base_mode, alt_mode, comp_ids):
    changes = []
    for i, cid in enumerate(comp_ids):
        if i < len(base_mode) and i < len(alt_mode) and base_mode[i] != alt_mode[i]:
            changes.append({"variable": cid, "from": int(base_mode[i]), "to": int(alt_mode[i])})
    return changes


def compact_top_hour_summary(row, forced_modes, forced_pump_on_hours, parsed_config):
    comp_ids = list(parsed_config["comp_ids"])
    active_ids = sorted(parsed_config["active_comps"])

    base_mode = tuple(row.get("base_mode", ()))
    alt_mode = tuple(row.get("alt_mode", ()))
    mode_change_rows = mode_changes(base_mode, alt_mode, comp_ids)

    component_candidates = {}
    for cid in active_ids:
        component_candidates[cid] = row.get(f"delta_P_{cid}", 0.0)
    primary_component = max(component_candidates, key=lambda k: abs(component_candidates[k]))
    primary_delta = component_candidates[primary_component]

    if mode_change_rows:
        hint_parts = []
        for ch in mode_change_rows:
            on_off = "on" if ch["to"] == 1 else "off"
            hint_parts.append(f"{ch['variable']} {on_off}")
        driver_hint = ", ".join(hint_parts)
    else:
        driver_hint = "no mode change"

    forced_assignments = {}
    for forced_mode in forced_modes:
        if "=" not in str(forced_mode):
            continue
        cid, value = str(forced_mode).split("=", 1)
        try:
            forced_assignments[cid.strip()] = int(value.strip())
        except (TypeError, ValueError):
            continue

    explanation = "Mode change rebalances the schedule."

    if base_mode != alt_mode:
        for ch in mode_change_rows:
            cid = ch["variable"]
            comp = parsed_config["components"][cid]
            cl = comp_label(cid, parsed_config)
            actor = "User" if forced_assignments.get(cid) == ch["to"] else "Optimizer"
            if ch["from"] == 1 and ch["to"] == 0:
                if comp["type"] == "pump":
                    explanation = (
                        f"{actor} turned {cl} off at this hour, "
                        f"saving energy consumption but potentially leaving less water for later."
                    )
                else:
                    explanation = (
                        f"{actor} turned {cl} off at this hour, "
                        f"conserving water but losing potential power generation."
                    )
                break
            if ch["from"] == 0 and ch["to"] == 1:
                if comp["type"] == "pump":
                    explanation = (
                        f"{actor} turned {cl} on at this hour, "
                        f"consuming energy now to store water for later."
                    )
                else:
                    explanation = (
                        f"{actor} turned {cl} on at this hour "
                        f"to generate more power."
                    )
                break
    elif base_mode == alt_mode:
        dn = row.get("delta_net", row.get("delta_net_power", 0.0))
        if abs(dn) < 1.0:
            explanation = "Small change from water-level shifts."
        else:
            explanation = f"Net power shifts by {dn:+,.1f} MW from water-level changes."

    return {
        "primary_component": primary_component,
        "primary_delta": primary_delta,
        "driver_hint": driver_hint,
        "explanation": explanation,
    }


def build_top_impacts_summary(user_constraints, top_rows, parsed_config, only_base=None, only_alt=None, in_both=None):
    comp_ids = sorted(parsed_config["comp_ids"])
    pump_ids = sorted(parsed_config["pumps"])

    normalized = normalize_user_constraints(user_constraints, comp_ids)
    forced_lookup = {}
    for cid, hour_map in normalized.items():
        for hour, value in hour_map.items():
            forced_lookup.setdefault(hour, []).append(f"{cid}={value}")

    forced_pump_on = []
    for pid in pump_ids:
        forced_pump_on.extend(
            hour for hour, val in normalized.get(pid, {}).items() if int(val) == 1
        )
    forced_pump_on.sort()

    out = []
    for rank, row in enumerate(top_rows, start=1):
        forced_modes = forced_lookup.get(row["hour"], [])
        delta_net = row.get("delta_net", row.get("delta_net_power", 0.0))
        out.append({
            "rank": rank,
            "hour": row["hour"],
            "delta_net_power": delta_net,
            "forced_modes": forced_modes,
            "summary": compact_top_hour_summary(row, forced_modes, forced_pump_on, parsed_config),
        })
    return out


def direction_label(value, tol=1e-9):
    if value > tol:
        return "increase"
    if value < -tol:
        return "decrease"
    return "no_change"


def overall_component_interpretation(component, objective_contribution, parsed_config):
    cl = comp_label(component, parsed_config)
    comp_type = parsed_config["components"][component]["type"]
    increasing = objective_contribution > 0
    if comp_type == "turbine":
        if increasing:
            return f"{cl} output increased and is the strongest positive contributor to net objective difference."
        return f"{cl} output decreased and is the strongest negative contributor to net objective difference."
    if comp_type == "pump":
        if increasing:
            return f"Reduced {cl} consumption is the strongest positive contributor to net objective difference."
        return f"Increased {cl} consumption is the strongest negative contributor to net objective difference."
    return "Largest contributor interpretation is unavailable."


def build_model_wide_largest_contributor(all_rows, parsed_config):
    if not all_rows:
        return {
            "largest_contributor": None,
            "component_deltas_total": {},
        }

    active_ids = sorted(parsed_config["active_comps"])
    turbine_ids = sorted(parsed_config["turbines"])
    pump_ids = sorted(parsed_config["pumps"])
    component_deltas = {}
    for cid in active_ids:
        component_deltas[cid] = sum(float(r.get(f"delta_P_{cid}", 0.0)) for r in all_rows)

    objective_contrib = {}
    for tid in turbine_ids:
        objective_contrib[tid] = component_deltas[tid]
    for pid in pump_ids:
        objective_contrib[pid] = -component_deltas[pid]

    largest = max(objective_contrib, key=lambda k: abs(objective_contrib[k]))

    return {
        "largest_contributor": {
            "component": largest,
            "objective_contribution": objective_contrib[largest],
            "interpretation": overall_component_interpretation(largest, objective_contrib[largest], parsed_config),
        },
        "component_deltas_total": component_deltas,
    }


def index_to_string(idx):
    if isinstance(idx, tuple):
        return "(" + ",".join(str(x) for x in idx) + ")"
    return str(idx)


def binding_constraint_explanation(constraint_name, iis_interp):
    family = iis_constraint_family(constraint_name)
    row = iis_interp.get(family, {})
    return row.get("interpretation", "Constraint-specific explanation is not available")


def binding_transition_interpretation(constraint_name, became_binding, binding_interp, non_binding_interp):
    family = iis_constraint_family(constraint_name)
    if became_binding:
        return binding_interp.get(family, "Binding interpretation is not available")
    return non_binding_interp.get(family, "Non-binding interpretation is not available")


def serializable_slack(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return value


def group_binding_with_interpretation(
    binding_rows,
    became_binding,
    iis_interp,
    binding_interp,
    non_binding_interp,
    slack_lookup=None,
):
    slack_lookup = slack_lookup or {}
    grouped = {}
    for name, idx, side in binding_rows:
        if name not in grouped:
            grouped[name] = {
                "constraint": name,
                "constraint_explanation": binding_constraint_explanation(name, iis_interp),
                "entries": [],
                "transition": "became_binding" if became_binding else "became_non_binding",
                "interpretation_for_constraint_status": binding_transition_interpretation(
                    name, became_binding, binding_interp, non_binding_interp,
                ),
            }
        entry = index_to_string(idx)
        grouped[name]["entries"].append(entry)
        key = (name, idx, side)
        if key in slack_lookup:
            grouped[name].setdefault("slack_values", []).append({
                "entry": entry,
                "side": side,
                "slack": serializable_slack(slack_lookup[key]),
            })
    return [grouped[name] for name in sorted(grouped)]


def build_feasibility_status(result_data):
    return {
        "p1_status": result_data["p1_status"],
        "p1_termination": result_data["p1_termination"],
        "p2_status": result_data["p2_status"],
        "p2_termination": result_data["p2_termination"],
        "p1_best_safety_violation": result_data.get("p1_best_safety_violation"),
        "p1_lock_tolerance": result_data.get("p1_lock_tolerance"),
        "final_safety_violation": result_data.get("total_safety_violation"),
        "solver_diagnostics": {
            "priority_1": result_data.get("p1_solver_diagnostics", {}),
            "priority_2": result_data.get("p2_solver_diagnostics", {}),
        },
        "is_optimal": (
            result_data["p1_termination"].lower() == "optimal"
            and result_data["p2_termination"].lower() == "optimal"
        ),
    }


def sanitize_infeasibility_diagnosis(diagnosis, iis_interp, parsed_config):
    if diagnosis is None:
        return None
    safe = {
        "is_infeasible": bool(diagnosis.get("is_infeasible", False)),
        "termination": diagnosis.get("termination"),
        "iis_method": diagnosis.get("iis_method"),
        "iis_note": diagnosis.get("iis_note"),
        "iis_forced": diagnosis.get("iis_forced", []),
        "iis_non_forced_constraints": explain_iis_constraints(
            diagnosis.get("iis_non_forced_constraints", []), iis_interp, parsed_config,
        ),
        "relaxation_pathways": [],
    }
    for path in diagnosis.get("relaxation_pathways", []):
        safe["relaxation_pathways"].append({
            "termination": path.get("termination"),
            "min_relax_count": path.get("min_relax_count"),
            "relaxed_atoms": path.get("relaxed_atoms", []),
            "feasibility_status": path.get("lexicographic_feasible"),
        })
    return safe


def inline_hour_lists(json_text):
    pattern = r'(^\s*"(hour|entries)": )\[\n(.*?)\n\s*\]'

    def replace(match):
        prefix = match.group(1)
        body = match.group(3)
        values = []
        for line in body.splitlines():
            item = line.strip()
            if not item:
                continue
            if item.endswith(","):
                item = item[:-1]
            values.append(item)
        return f"{prefix}[{', '.join(values)}]"

    return re.sub(pattern, replace, json_text, flags=re.DOTALL | re.MULTILINE)


def build_summary_payload(
    baseline_result,
    alternative_result,
    user_constraints,
    spill_control,
    all_rows,
    top_rows,
    only_base,
    only_alt,
    in_both,
    parsed_config,
    only_base_slacks=None,
    only_alt_slacks=None,
    in_both_slacks=None,
    binding_tolerance=None,
    infeasibility_diagnosis=None,
):
    iis_interp = build_iis_constraint_interpretation(parsed_config)
    binding_interp, non_binding_interp = build_binding_interpretation(parsed_config)
    baseline_net = baseline_result["total_generation_power"]
    baseline_revenue = baseline_result.get("total_revenue_eur", 0.0)

    payload = {
        "A_baseline": {
            "horizon_hours": len(baseline_result.get("hourly", [])),
            "feasibility_status": build_feasibility_status(baseline_result),
            "lexicographic_objectives": baseline_result.get("lexicographic_objectives", []),
            "power": {
                "power_generated": baseline_result["total_gen"],
                "power_consumed": baseline_result["total_pump"],
                "net_power": baseline_net,
            },
            "revenue_eur": baseline_revenue,
        },
        "B_user_alternative": None,
    }

    if alternative_result is not None:
        alt_net = alternative_result["total_generation_power"]
        alt_revenue = alternative_result.get("total_revenue_eur", 0.0)
        delta_net = alt_net - baseline_net
        delta_revenue = alt_revenue - baseline_revenue
        pct = (delta_net / baseline_net * 100.0) if abs(baseline_net) > 1e-9 else None

        payload["B_user_alternative"] = {
            "change_from_user_request": format_user_request_changes(
                user_constraints, spill_control, parsed_config,
            ),
            "feasibility_status": build_feasibility_status(alternative_result),
            "lexicographic_objectives": alternative_result.get("lexicographic_objectives", []),
            "power": {
                "power_generated": alternative_result["total_gen"],
                "power_consumed": alternative_result["total_pump"],
                "net_power": alt_net,
            },
            "revenue_eur": alt_revenue,
            "delta_from_baseline": {
                "delta_net_power": delta_net,
                "percent_change_net_power": pct,
                "delta_revenue_eur": delta_revenue,
            },
        }

        top_hours = []
        if abs(delta_net) > 1e-9:
            top_hours = build_top_impacts_summary(
                user_constraints, top_rows[:3], parsed_config,
                only_base=only_base, only_alt=only_alt, in_both=in_both,
            )
        payload["C_top_impacts"] = {
            "model_wide_largest_contributor": build_model_wide_largest_contributor(all_rows, parsed_config),
            "top_hours": top_hours,
        }
        payload["D_binding_constraints"] = {
            "counts": {
                "binding_in_both": len(in_both),
                "only_in_baseline": len(only_base),
                "only_in_alternative": len(only_alt),
            },
            "binding_tolerance": binding_tolerance,
            "new_bottlenecks_in_alternative": group_binding_with_interpretation(
                only_alt,
                True,
                iis_interp,
                binding_interp,
                non_binding_interp,
                slack_lookup=only_alt_slacks,
            ),
            "released_from_baseline": group_binding_with_interpretation(
                only_base,
                False,
                iis_interp,
                binding_interp,
                non_binding_interp,
                slack_lookup=only_base_slacks,
            ),
        }

    elif infeasibility_diagnosis is not None:
        payload["B_user_alternative"] = {
            "change_from_user_request": format_user_request_changes(
                user_constraints, spill_control, parsed_config,
            ),
            "feasibility_status": {
                "p1_status": "n/a",
                "p1_termination": str(infeasibility_diagnosis.get("termination", "infeasible")),
                "p2_status": "n/a",
                "p2_termination": "not_run",
                "is_optimal": False,
            },
            "power": {"power_generated": None, "power_consumed": None, "net_power": None},
            "delta_from_baseline": {"delta_net_power": None, "percent_change_net_power": None},
        }
        payload["C_iis_diagnosis"] = sanitize_infeasibility_diagnosis(
            infeasibility_diagnosis, iis_interp, parsed_config,
        )

    return payload


def write_reports(summary_payload, report_prefix=None, output_folder="reports"):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    prefix = str(report_prefix).strip() if report_prefix is not None else "model_run_report"
    if not prefix:
        prefix = "model_run_report"
    output_dir = Path(output_folder or "reports")
    output_dir.mkdir(parents=True, exist_ok=True)

    json_path = output_dir / f"{prefix}_{timestamp}.json"
    json_payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "summary": summary_payload,
    }
    json_text = json.dumps(json_payload, indent=2)
    json_text = inline_hour_lists(json_text)
    json_path.write_text(json_text, encoding="utf-8")
    return json_path


def generate_diagnostic_report(
    run_outputs,
    user_constraints,
    spill_control,
    parsed_config,
    feasible_diag=None,
    infeasible_diag=None,
    report_prefix=None,
    output_folder="reports",
):
    baseline_result = run_outputs["baseline_result"]
    alternative_result = (
        run_outputs["alternative"]["result"]
        if run_outputs["alternative"]["is_feasible"]
        else None
    )

    all_rows = feasible_diag.get("all_rows", []) if feasible_diag else []
    top_rows = feasible_diag["top_rows"] if feasible_diag else []
    only_base = feasible_diag["only_base"] if feasible_diag else []
    only_alt = feasible_diag["only_alt"] if feasible_diag else []
    in_both = feasible_diag["in_both"] if feasible_diag else []
    only_base_slacks = feasible_diag.get("only_base_slacks", {}) if feasible_diag else {}
    only_alt_slacks = feasible_diag.get("only_alt_slacks", {}) if feasible_diag else {}
    in_both_slacks = feasible_diag.get("in_both_slacks", {}) if feasible_diag else {}
    binding_tolerance = feasible_diag.get("binding_tolerance") if feasible_diag else None

    summary_payload = build_summary_payload(
        baseline_result=baseline_result,
        alternative_result=alternative_result,
        user_constraints=user_constraints,
        spill_control=spill_control,
        all_rows=all_rows,
        top_rows=top_rows,
        only_base=only_base,
        only_alt=only_alt,
        in_both=in_both,
        parsed_config=parsed_config,
        only_base_slacks=only_base_slacks,
        only_alt_slacks=only_alt_slacks,
        in_both_slacks=in_both_slacks,
        binding_tolerance=binding_tolerance,
        infeasibility_diagnosis=infeasible_diag,
    )

    json_path = write_reports(
        summary_payload,
        report_prefix=report_prefix,
        output_folder=output_folder,
    )

    return {
        "json_path": str(json_path),
        "summary_payload": summary_payload,
    }
